version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/the-happy-record
      - INIT_DB=true

volumes:
  mongodb_data: