name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: Start the application
      run: npm run start > app.log 2>&1
      continue-on-error: true
    - name: Check for successful start
      run: |
        if grep -q "Running at Port 4000" app.log; then
          echo "Success"
          exit 0
        else
          echo "Failed"
          exit 1
        fi
