name: Deploy on VPS
on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  deploy:      
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOST }}
        name: id_rsa
        if_key_exists: fail
    - name: Connect to VPS and Deploy
      run: ssh root@${{ secrets.SSH_HOST }} "cd /root/The-Happy-Record && docker-compose down && git checkout main && git pull && docker-compose build --no-cache && docker-compose up -d && netstat -ant && exit" > deploy.log"
    - name: Check for successful start
      run: |
        if grep -q "4000" deploy.log; then
          echo "Success"
          exit 0
        else
          echo "Failed"
          exit 1
        fi